// ─── Master Tool List ─────────────────────────────────────────────────────────
// Add a new tool here and it automatically appears on the homepage, in related
// tools, in the sitemap, and in the breadcrumb nav.
//
// Fields:
//   id          — unique slug (also used as ICON_MAP key and URL segment)
//   title       — human-readable name
//   description — one-line summary shown on cards and related-tool lists
//   icon        — emoji fallback (shown when no SVG icon exists in ICON_MAP)
//   category    — Images | PDF | Text | Developer | SEO | Security | Calculator | Utility
//   path        — must be '/tools/{id}'
//   type        — 'frontend' | 'backend'
//   keywords    — search keywords used by the homepage search filter

export const TOOLS = [

  // ── Images ──────────────────────────────────────────────────────────────────
  {
    id: 'compress-image',
    title: 'Image Compressor',
    description: 'Reduce image file size without losing quality. Supports JPG, PNG, WebP, AVIF.',
    icon: '🗜️',
    category: 'Images',
    path: '/tools/compress-image',
    type: 'backend',
    keywords: ['compress', 'reduce', 'optimize', 'image', 'jpg', 'png', 'webp'],
  },
  {
    id: 'resize-image',
    title: 'Image Resizer',
    description: 'Resize images to any dimension. Maintain aspect ratio automatically.',
    icon: '📐',
    category: 'Images',
    path: '/tools/resize-image',
    type: 'backend',
    keywords: ['resize', 'scale', 'dimension', 'width', 'height', 'image'],
  },
  {
    id: 'convert-image',
    title: 'Image Converter',
    description: 'Convert images between JPG, PNG, WebP, and AVIF formats instantly.',
    icon: '🔄',
    category: 'Images',
    path: '/tools/convert-image',
    type: 'backend',
    keywords: ['convert', 'format', 'webp', 'avif', 'png', 'jpg', 'image'],
  },
  {
    id: 'base64-image',
    title: 'Base64 Image Encoder',
    description: 'Convert images to Base64 strings for embedding in HTML, CSS, or JSON.',
    icon: '🖼️',
    category: 'Images',
    path: '/tools/base64-image',
    type: 'frontend',
    keywords: ['base64', 'image', 'encode', 'data uri', 'embed', 'inline'],
  },
  {
    id: 'image-crop',
    title: 'Image Crop Tool',
    description: 'Crop images to any size or aspect ratio directly in your browser.',
    icon: '✂️',
    category: 'Images',
    path: '/tools/image-crop',
    type: 'frontend',
    keywords: ['crop', 'trim', 'image', 'aspect ratio', 'cut'],
  },
  {
    id: 'svg-optimizer',
    title: 'SVG Optimizer',
    description: 'Clean and minify SVG files to reduce file size without losing quality.',
    icon: '⚡',
    category: 'Images',
    path: '/tools/svg-optimizer',
    type: 'frontend',
    keywords: ['svg', 'optimize', 'minify', 'clean', 'vector'],
  },

  // ── PDF ─────────────────────────────────────────────────────────────────────
  {
    id: 'merge-pdfs',
    title: 'PDF Merger',
    description: 'Combine multiple PDF files into one. Up to 10 files at once.',
    icon: '📄',
    category: 'PDF',
    path: '/tools/merge-pdfs',
    type: 'backend',
    keywords: ['merge', 'combine', 'pdf', 'join'],
  },
  {
    id: 'split-pdf',
    title: 'PDF Splitter',
    description: 'Split a PDF into individual pages or extract a specific page range.',
    icon: '✂️',
    category: 'PDF',
    path: '/tools/split-pdf',
    type: 'backend',
    keywords: ['split', 'extract', 'pdf', 'pages', 'separate'],
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    description: 'Convert one or multiple images into a single PDF document.',
    icon: '🖼️',
    category: 'PDF',
    path: '/tools/image-to-pdf',
    type: 'backend',
    keywords: ['image', 'pdf', 'convert', 'jpg to pdf', 'png to pdf'],
  },
  {
    id: 'pdf-page-counter',
    title: 'PDF Page Counter',
    description: 'Count the number of pages in a PDF file instantly without uploading.',
    icon: '🔢',
    category: 'PDF',
    path: '/tools/pdf-page-counter',
    type: 'frontend',
    keywords: ['pdf', 'page count', 'pages', 'pdf info'],
  },
  {
    id: 'pdf-metadata',
    title: 'PDF Metadata Viewer',
    description: 'View PDF metadata: title, author, creation date, and more.',
    icon: '📋',
    category: 'PDF',
    path: '/tools/pdf-metadata',
    type: 'frontend',
    keywords: ['pdf', 'metadata', 'author', 'title', 'info', 'properties'],
  },

  // ── Text ────────────────────────────────────────────────────────────────────
  {
    id: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences and paragraphs in your text.',
    icon: '📝',
    category: 'Text',
    path: '/tools/word-counter',
    type: 'frontend',
    keywords: ['word', 'count', 'character', 'text', 'sentence', 'paragraph'],
  },
  {
    id: 'slug-generator',
    title: 'Slug Generator',
    description: 'Convert any text into a clean, URL-friendly slug for SEO-optimised links.',
    icon: '🔗',
    category: 'Text',
    path: '/tools/slug-generator',
    type: 'frontend',
    keywords: ['slug', 'url', 'permalink', 'seo', 'hyphen', 'url-friendly'],
  },
  {
    id: 'text-case-converter',
    title: 'Text Case Converter',
    description: 'Convert text to UPPERCASE, lowercase, Title Case, camelCase, snake_case and more.',
    icon: 'Aa',
    category: 'Text',
    path: '/tools/text-case-converter',
    type: 'frontend',
    keywords: ['uppercase', 'lowercase', 'camelcase', 'snake_case', 'title case', 'case converter'],
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum Generator',
    description: 'Generate Lorem Ipsum placeholder text — paragraphs, sentences, or words.',
    icon: '📄',
    category: 'Text',
    path: '/tools/lorem-ipsum',
    type: 'frontend',
    keywords: ['lorem ipsum', 'placeholder', 'dummy text', 'filler text', 'blind text'],
  },
  {
    id: 'text-diff',
    title: 'Text Diff Checker',
    description: 'Compare two texts and highlight the differences line by line.',
    icon: '↔️',
    category: 'Text',
    path: '/tools/text-diff',
    type: 'frontend',
    keywords: ['diff', 'compare', 'text', 'difference', 'changes'],
  },
  {
    id: 'duplicate-line-remover',
    title: 'Duplicate Line Remover',
    description: 'Remove duplicate lines from any text. Sort and deduplicate lists instantly.',
    icon: '🧹',
    category: 'Text',
    path: '/tools/duplicate-line-remover',
    type: 'frontend',
    keywords: ['duplicate', 'remove', 'lines', 'unique', 'deduplicate'],
  },
  {
    id: 'markdown-to-html',
    title: 'Markdown to HTML',
    description: 'Convert Markdown syntax to clean HTML. Live preview included.',
    icon: '⬇️',
    category: 'Text',
    path: '/tools/markdown-to-html',
    type: 'frontend',
    keywords: ['markdown', 'html', 'convert', 'md', 'preview'],
  },
  {
    id: 'html-to-text',
    title: 'HTML to Plain Text',
    description: 'Strip HTML tags and convert HTML to readable plain text.',
    icon: '🧼',
    category: 'Text',
    path: '/tools/html-to-text',
    type: 'frontend',
    keywords: ['html', 'strip', 'text', 'remove tags', 'plain text'],
  },
  {
    id: 'email-extractor',
    title: 'Email Extractor',
    description: 'Extract all email addresses from any block of text or HTML.',
    icon: '📧',
    category: 'Text',
    path: '/tools/email-extractor',
    type: 'frontend',
    keywords: ['email', 'extract', 'find', 'regex', 'scrape'],
  },

  // ── Developer ────────────────────────────────────────────────────────────────
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Beautify, minify, and validate JSON. Syntax highlighting included.',
    icon: '{ }',
    category: 'Developer',
    path: '/tools/json-formatter',
    type: 'frontend',
    keywords: ['json', 'format', 'beautify', 'validate', 'minify', 'pretty print'],
  },
  {
    id: 'base64',
    title: 'Base64 Encoder/Decoder',
    description: 'Encode or decode text and files to/from Base64 format.',
    icon: '🔢',
    category: 'Developer',
    path: '/tools/base64',
    type: 'frontend',
    keywords: ['base64', 'encode', 'decode', 'binary'],
  },
  {
    id: 'url-encoder',
    title: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs and query string parameters instantly.',
    icon: '🔗',
    category: 'Developer',
    path: '/tools/url-encoder',
    type: 'frontend',
    keywords: ['url', 'encode', 'decode', 'uri', 'query', 'percent encoding'],
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL formats with a live picker.',
    icon: '🎨',
    category: 'Developer',
    path: '/tools/color-converter',
    type: 'frontend',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'colour'],
  },
  {
    id: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate RFC 4122 v4 UUIDs using a cryptographically secure random generator.',
    icon: '🔑',
    category: 'Developer',
    path: '/tools/uuid-generator',
    type: 'frontend',
    keywords: ['uuid', 'guid', 'unique id', 'random', 'v4', 'identifier'],
  },
  {
    id: 'timestamp-converter',
    title: 'Timestamp Converter',
    description: 'Convert Unix timestamps to dates and dates to Unix timestamps. Live clock.',
    icon: '⏱️',
    category: 'Developer',
    path: '/tools/timestamp-converter',
    type: 'frontend',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert'],
  },
  {
    id: 'html-entity-encoder',
    title: 'HTML Entity Encoder',
    description: 'Encode and decode HTML entities. Convert &, <, > and special characters.',
    icon: '&lt;',
    category: 'Developer',
    path: '/tools/html-entity-encoder',
    type: 'frontend',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'unescape', 'ampersand'],
  },
  {
    id: 'url-parser',
    title: 'URL Parser',
    description: 'Parse URLs into protocol, host, path, query parameters and hash fragment.',
    icon: '🔍',
    category: 'Developer',
    path: '/tools/url-parser',
    type: 'frontend',
    keywords: ['url', 'parse', 'query string', 'parameters', 'href', 'analyze'],
  },
  {
    id: 'jwt-decoder',
    title: 'JWT Decoder',
    description: 'Decode JSON Web Tokens and inspect header, payload and expiration status.',
    icon: '🪙',
    category: 'Developer',
    path: '/tools/jwt-decoder',
    type: 'frontend',
    keywords: ['jwt', 'json web token', 'decode', 'bearer', 'auth token', 'payload'],
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    description: 'Test regular expressions with real-time match highlighting and group inspection.',
    icon: '.*',
    category: 'Developer',
    path: '/tools/regex-tester',
    type: 'frontend',
    keywords: ['regex', 'regexp', 'regular expression', 'pattern', 'match', 'test'],
  },
  {
    id: 'json-to-csv',
    title: 'JSON to CSV Converter',
    description: 'Convert a JSON array of objects to a properly formatted CSV file.',
    icon: '📊',
    category: 'Developer',
    path: '/tools/json-to-csv',
    type: 'frontend',
    keywords: ['json', 'csv', 'convert', 'export', 'spreadsheet', 'data'],
  },
  {
    id: 'csv-to-json',
    title: 'CSV to JSON Converter',
    description: 'Convert CSV data to a JSON array. Paste CSV and get JSON instantly.',
    icon: '📋',
    category: 'Developer',
    path: '/tools/csv-to-json',
    type: 'frontend',
    keywords: ['csv', 'json', 'convert', 'import', 'parse', 'data'],
  },
  {
    id: 'binary-converter',
    title: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal and hexadecimal bases.',
    icon: '01',
    category: 'Developer',
    path: '/tools/binary-converter',
    type: 'frontend',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'base', 'convert', 'number'],
  },
  {
    id: 'roman-numeral',
    title: 'Roman Numeral Converter',
    description: 'Convert between Roman numerals and decimal numbers instantly.',
    icon: 'Ⅻ',
    category: 'Developer',
    path: '/tools/roman-numeral',
    type: 'frontend',
    keywords: ['roman', 'numeral', 'convert', 'decimal', 'roman numerals'],
  },
  {
    id: 'js-minifier',
    title: 'JS / CSS Minifier',
    description: 'Minify JavaScript or CSS code to reduce file size and improve load times.',
    icon: '⚡',
    category: 'Developer',
    path: '/tools/js-minifier',
    type: 'frontend',
    keywords: ['minify', 'compress', 'javascript', 'css', 'optimize', 'bundle'],
  },
  {
    id: 'cron-generator',
    title: 'Cron Expression Generator',
    description: 'Build and validate cron expressions with a visual editor and plain-English description.',
    icon: '🕐',
    category: 'Developer',
    path: '/tools/cron-generator',
    type: 'frontend',
    keywords: ['cron', 'schedule', 'expression', 'crontab', 'job', 'recurring'],
  },

  // ── SEO ─────────────────────────────────────────────────────────────────────
  {
    id: 'meta-tag-generator',
    title: 'Meta Tag Generator',
    description: 'Generate HTML meta tags for SEO: title, description, Open Graph, and Twitter.',
    icon: '🏷️',
    category: 'SEO',
    path: '/tools/meta-tag-generator',
    type: 'frontend',
    keywords: ['meta tags', 'seo', 'title tag', 'description', 'html head', 'generator'],
  },
  {
    id: 'og-generator',
    title: 'Open Graph Generator',
    description: 'Generate Open Graph meta tags for better social media sharing previews.',
    icon: '📱',
    category: 'SEO',
    path: '/tools/og-generator',
    type: 'frontend',
    keywords: ['open graph', 'og tags', 'facebook', 'twitter card', 'social media', 'seo'],
  },
  {
    id: 'robots-generator',
    title: 'Robots.txt Generator',
    description: 'Build a custom robots.txt file to control how search engines crawl your site.',
    icon: '🤖',
    category: 'SEO',
    path: '/tools/robots-generator',
    type: 'frontend',
    keywords: ['robots.txt', 'crawl', 'disallow', 'sitemap', 'seo', 'bot'],
  },
  {
    id: 'keyword-density',
    title: 'Keyword Density Checker',
    description: 'Analyse keyword frequency and density in your content for on-page SEO.',
    icon: '📈',
    category: 'SEO',
    path: '/tools/keyword-density',
    type: 'frontend',
    keywords: ['keyword density', 'seo', 'keyword frequency', 'content analysis', 'on-page seo'],
  },
  {
    id: 'sitemap-generator',
    title: 'Sitemap Generator',
    description: 'Generate an XML sitemap by entering your website URLs. Download instantly.',
    icon: '🗺️',
    category: 'SEO',
    path: '/tools/sitemap-generator',
    type: 'frontend',
    keywords: ['sitemap', 'xml sitemap', 'seo', 'google', 'urls', 'search engine'],
  },

  // ── Security ─────────────────────────────────────────────────────────────────
  {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Generate strong, secure passwords with customisable options.',
    icon: '🔐',
    category: 'Security',
    path: '/tools/password-generator',
    type: 'frontend',
    keywords: ['password', 'generate', 'secure', 'random', 'strong'],
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    description: 'Generate SHA-256 or SHA-512 hashes from any text input via Web Crypto API.',
    icon: '#',
    category: 'Security',
    path: '/tools/hash-generator',
    type: 'frontend',
    keywords: ['hash', 'sha', 'sha256', 'sha512', 'crypto', 'checksum'],
  },
  {
    id: 'password-strength',
    title: 'Password Strength Checker',
    description: 'Check the strength of any password with an instant security analysis.',
    icon: '🛡️',
    category: 'Security',
    path: '/tools/password-strength',
    type: 'frontend',
    keywords: ['password strength', 'security', 'check', 'strong password', 'weak password'],
  },
  {
    id: 'hash-compare',
    title: 'Hash Compare Tool',
    description: 'Compare two hash strings to verify file integrity or password matches.',
    icon: '🔍',
    category: 'Security',
    path: '/tools/hash-compare',
    type: 'frontend',
    keywords: ['hash', 'compare', 'checksum', 'integrity', 'md5', 'sha'],
  },
  {
    id: 'uuid-validator',
    title: 'UUID Validator',
    description: 'Validate UUID strings and detect their version (v1, v4, v5, etc.).',
    icon: '✅',
    category: 'Security',
    path: '/tools/uuid-validator',
    type: 'frontend',
    keywords: ['uuid', 'guid', 'validate', 'verify', 'version', 'format'],
  },

  // ── Calculator ───────────────────────────────────────────────────────────────
  {
    id: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate exact age in years, months, and days from any date of birth.',
    icon: '🎂',
    category: 'Calculator',
    path: '/tools/age-calculator',
    type: 'frontend',
    keywords: ['age', 'calculator', 'date of birth', 'birthday', 'years old'],
  },
  {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    description: 'Calculate your Body Mass Index with metric or imperial units.',
    icon: '⚖️',
    category: 'Calculator',
    path: '/tools/bmi-calculator',
    type: 'frontend',
    keywords: ['bmi', 'body mass index', 'weight', 'height', 'health'],
  },
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    description: 'Calculate percentages, percentage change, and find what percent X is of Y.',
    icon: '%',
    category: 'Calculator',
    path: '/tools/percentage-calculator',
    type: 'frontend',
    keywords: ['percentage', 'percent', 'calculate', 'discount', 'increase', 'decrease'],
  },
  {
    id: 'emi-calculator',
    title: 'EMI / Loan Calculator',
    description: 'Calculate monthly loan payments, total interest, and amortisation schedule.',
    icon: '🏦',
    category: 'Calculator',
    path: '/tools/emi-calculator',
    type: 'frontend',
    keywords: ['emi', 'loan', 'mortgage', 'interest', 'monthly payment', 'amortization'],
  },
  {
    id: 'tip-calculator',
    title: 'Tip Calculator',
    description: 'Calculate tip amount and split the bill among any number of people.',
    icon: '🧾',
    category: 'Calculator',
    path: '/tools/tip-calculator',
    type: 'frontend',
    keywords: ['tip', 'gratuity', 'bill', 'split', 'restaurant', 'calculator'],
  },

  // ── Utility ──────────────────────────────────────────────────────────────────
  {
    id: 'qr-generator',
    title: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, or contact info. Download as PNG.',
    icon: '⬛',
    category: 'Utility',
    path: '/tools/qr-generator',
    type: 'frontend',
    keywords: ['qr', 'qrcode', 'barcode', 'scan', 'generate'],
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert between length, weight, temperature, area and data units.',
    icon: '📏',
    category: 'Utility',
    path: '/tools/unit-converter',
    type: 'frontend',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'metric'],
  },
  {
    id: 'timezone-converter',
    title: 'Timezone Converter',
    description: 'Convert time between world timezones. Find the overlap for your team.',
    icon: '🌍',
    category: 'Utility',
    path: '/tools/timezone-converter',
    type: 'frontend',
    keywords: ['timezone', 'time zone', 'convert', 'utc', 'gmt', 'world clock'],
  },
  {
    id: 'random-number',
    title: 'Random Number Generator',
    description: 'Generate random numbers within any range. Single or bulk generation.',
    icon: '🎲',
    category: 'Utility',
    path: '/tools/random-number',
    type: 'frontend',
    keywords: ['random', 'number', 'generate', 'dice', 'lottery', 'range'],
  },
  {
    id: 'random-name',
    title: 'Random Name Generator',
    description: 'Generate random names for testing, games, or fiction writing.',
    icon: '👤',
    category: 'Utility',
    path: '/tools/random-name',
    type: 'frontend',
    keywords: ['random name', 'name generator', 'fake name', 'username', 'character name'],
  },
  {
    id: 'user-agent-parser',
    title: 'User Agent Parser',
    description: 'Parse and decode user agent strings to identify browser, OS, and device.',
    icon: '🖥️',
    category: 'Utility',
    path: '/tools/user-agent-parser',
    type: 'frontend',
    keywords: ['user agent', 'browser', 'os', 'device', 'parse', 'detect'],
  },
  {
    id: 'color-palette',
    title: 'Color Palette Generator',
    description: 'Generate harmonious color palettes from a base color. Export as CSS.',
    icon: '🎨',
    category: 'Utility',
    path: '/tools/color-palette',
    type: 'frontend',
    keywords: ['color palette', 'colors', 'complementary', 'design', 'css', 'theme'],
  },
  {
    id: 'aspect-ratio',
    title: 'Aspect Ratio Calculator',
    description: 'Calculate and maintain aspect ratios for images, videos, and responsive design.',
    icon: '📺',
    category: 'Utility',
    path: '/tools/aspect-ratio',
    type: 'frontend',
    keywords: ['aspect ratio', 'width', 'height', '16:9', 'responsive', 'video'],
  },
  {
    id: 'countdown-timer',
    title: 'Countdown Timer',
    description: 'Set a countdown to any date and share it with a link. Runs in your browser.',
    icon: '⏳',
    category: 'Utility',
    path: '/tools/countdown-timer',
    type: 'frontend',
    keywords: ['countdown', 'timer', 'date', 'event', 'days left'],
  },
];

export const CATEGORIES = [...new Set(TOOLS.map(t => t.category))];
