import { useState, useCallback } from 'react';
import ToolLayout from '../../components/common/ToolLayout';
import Button from '../../components/common/Button';
import { PasswordGeneratorIcon } from '../../components/common/Icons';
import { useSEO, buildToolSchema, buildFAQSchema } from '../../utils/useSEO';

const CHARS = {
  uppercase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  lowercase: 'abcdefghijklmnopqrstuvwxyz',
  numbers: '0123456789',
  symbols: '!@#$%^&*()_+-=[]{}|;:,.<>?',
};

function getStrength(password) {
  let score = 0;
  if (password.length >= 8) score++;
  if (password.length >= 12) score++;
  if (password.length >= 16) score++;
  if (/[A-Z]/.test(password)) score++;
  if (/[a-z]/.test(password)) score++;
  if (/[0-9]/.test(password)) score++;
  if (/[^A-Za-z0-9]/.test(password)) score++;
  if (score <= 2) return { label: 'Weak', color: 'bg-red-500', width: '25%' };
  if (score <= 4) return { label: 'Fair', color: 'bg-yellow-500', width: '50%' };
  if (score <= 5) return { label: 'Good', color: 'bg-blue-500', width: '75%' };
  return { label: 'Strong', color: 'bg-green-500', width: '100%' };
}

const seoContent = {
  about: 'The Tooli Password Generator creates cryptographically secure random passwords using the browser\'s built-in Web Crypto API (crypto.getRandomValues). It never uses Math.random(), which is not cryptographically secure. You can customise the length (4–128 characters) and character set, and generate up to 10 passwords at once.',
  howTo: [
    'Set the desired password length using the slider (4 to 128 characters).',
    'Choose which character types to include: uppercase, lowercase, numbers, and/or symbols.',
    'Select how many passwords to generate (1–10).',
    'Click "Generate Password" and copy any result with the "Copy" button.',
  ],
  features: [
    'Cryptographically secure using Web Crypto API',
    'Customisable length from 4 to 128 characters',
    'Choose from uppercase, lowercase, numbers, and symbols',
    'Generate up to 10 passwords at once',
    'Password strength indicator',
    'Runs entirely in your browser — never sent to a server',
  ],
  faq: [
    { q: 'How secure are the generated passwords?', a: 'Passwords are generated using crypto.getRandomValues(), which is the browser\'s cryptographically secure pseudorandom number generator (CSPRNG). They are as secure as passwords generated by dedicated password managers.' },
    { q: 'Are my passwords stored or logged?', a: 'No. Password generation runs entirely in your browser. Nothing is sent to any server. Refreshing the page clears all generated passwords.' },
    { q: 'What length should I use?', a: 'For most accounts, 16 characters with a mix of all character types is excellent. For highly sensitive accounts (email, banking), 20+ characters is recommended.' },
  ],
};

export default function PasswordGenerator() {
  const [length, setLength] = useState(16);
  const [options, setOptions] = useState({ uppercase: true, lowercase: true, numbers: true, symbols: false });
  const [passwords, setPasswords] = useState([]);
  const [count, setCount] = useState(1);
  const [copied, setCopied] = useState(null);

  useSEO({
    title: 'Password Generator',
    description: 'Generate strong, secure, random passwords. Customize length and character types.',
    keywords: ['password generator', 'strong password', 'random password', 'secure password generator'],
    jsonLd: [buildToolSchema({ name: 'Password Generator', description: 'Generate strong, cryptographically secure passwords online', url: '/tools/password-generator' }), buildFAQSchema(seoContent.faq)],
    canonical: '/tools/password-generator',
  });

  const generate = useCallback(() => {
    let chars = '';
    Object.entries(options).forEach(([key, enabled]) => {
      if (enabled) chars += CHARS[key];
    });
    if (!chars) { chars = CHARS.lowercase; }

    const arr = [];
    for (let p = 0; p < count; p++) {
      const bytes = new Uint8Array(length);
      crypto.getRandomValues(bytes);
      arr.push(Array.from(bytes).map(b => chars[b % chars.length]).join(''));
    }
    setPasswords(arr);
    setCopied(null);
  }, [length, options, count]);

  const copy = async (pw, idx) => {
    await navigator.clipboard.writeText(pw);
    setCopied(idx);
    setTimeout(() => setCopied(null), 2000);
  };

  const toggle = (key) => setOptions(o => ({ ...o, [key]: !o[key] }));

  const strength = passwords[0] ? getStrength(passwords[0]) : null;

  return (
    <ToolLayout
      title="Password Generator"
      description="Generate strong, secure passwords with full customisation."
      icon={<PasswordGeneratorIcon className="w-6 h-6" />}
      category="Security"
      seoContent={seoContent}
    >
      <div className="card space-y-5">
        {/* Length */}
        <div>
          <label className="label">
            Password Length: <span className="text-blue-600 font-bold">{length}</span>
          </label>
          <input type="range" min={4} max={128} value={length}
            onChange={e => setLength(+e.target.value)} className="w-full accent-blue-600" />
          <div className="flex justify-between text-xs text-gray-400 mt-1"><span>4</span><span>128</span></div>
        </div>

        {/* Options */}
        <div>
          <label className="label">Character Types</label>
          <div className="grid grid-cols-2 gap-2">
            {Object.entries(CHARS).map(([key, example]) => (
              <label key={key} className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors">
                <input type="checkbox" checked={options[key]} onChange={() => toggle(key)}
                  className="w-4 h-4 accent-blue-600" />
                <div>
                  <div className="text-sm font-medium capitalize">{key}</div>
                  <div className="text-xs text-gray-400 font-mono">{example.slice(0, 12)}…</div>
                </div>
              </label>
            ))}
          </div>
        </div>

        {/* Count */}
        <div>
          <label className="label">Number of passwords: <span className="text-blue-600 font-bold">{count}</span></label>
          <input type="range" min={1} max={10} value={count}
            onChange={e => setCount(+e.target.value)} className="w-full accent-blue-600" />
        </div>

        <Button onClick={generate} className="w-full" size="lg">Generate Password{count > 1 ? 's' : ''}</Button>
      </div>

      {passwords.length > 0 && (
        <div className="card space-y-3">
          {strength && (
            <div className="mb-2">
              <div className="flex justify-between text-xs text-gray-500 mb-1">
                <span>Strength</span><span className="font-medium">{strength.label}</span>
              </div>
              <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                <div className={`h-full ${strength.color} transition-all rounded-full`} style={{ width: strength.width }} />
              </div>
            </div>
          )}

          {passwords.map((pw, i) => (
            <div key={i} className="flex items-center gap-3 p-3 bg-gray-50 rounded-xl border">
              <code className="flex-1 text-sm font-mono break-all text-gray-800">{pw}</code>
              <button
                onClick={() => copy(pw, i)}
                className="shrink-0 px-3 py-1.5 text-xs bg-white border rounded-lg hover:bg-blue-50 hover:border-blue-300 transition-colors"
              >
                {copied === i ? '✅' : 'Copy'}
              </button>
            </div>
          ))}
        </div>
      )}
    </ToolLayout>
  );
}
